name: autodeployment with git-action

on:
  push:
    branches:
      - main
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: github repository 소스 가져오기
        uses: actions/checkout@v4

      - name: JDK17 설치하기
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application yml 추가하기
        run: |
          mkdir -p src/main/resources || true
          echo "${{secrets.APPLICATION_YML}}" > ./src/main/resources/application.yml
          cat ./src/main/resources/application.yml

      - name: jar 파일 생성 (build)
        run: |
          chmod +x ./gradlew # 실행권한 추가
          ./gradlew clean build

      - name: 빌드된 jar 파일 이름을 app.jar로 변경 및 이동
        run: |
          pwd
          mv ./build/libs/*SNAPSHOT.jar ./app.jar
          ls -al

      - name: EC2로 jar파일을 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_KEY}}
          source: ./app.jar
          target: /home/ubuntu/prod/tobe

  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: 현재 실행중인 프로세스 중지하고 새로운 프로세스 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_KEY}}
          script_stop: true
          script: |
            sudo fuser -k -n tcp 8080 || true
            rm -rf /home/ubuntu/prod/cur || true
            mkdir /home/ubuntu/prod/cur
            cd /home/ubuntu/prod/cur
            mv ../tobe/app.jar .
            sudo nohup java -jar app.jar > ./output.log 2>&1 &